### ISSUE TITLE
Breaks with en-GB locale

### ISSUE THREAD

**Issue by jackwilsdon** [Haroenv/read-one-article#12]
For browsers with the `en-GB` locale, `i18n.language` ends up being `en-GB` here: https://github.com/Haroenv/read-one-article/blob/bf6d7bbac2dc9eef54898ee4ab94a55bf82293f8/src/App.js#L653-L657

Which means we end up making a request to https://en-gb.wikipedia.org:

https://github.com/Haroenv/read-one-article/blob/bf6d7bbac2dc9eef54898ee4ab94a55bf82293f8/src/App.js#L28

Which doesn't exist: https://en-gb.wikipedia.org

**Comment by Haroenv** [comment]
Pretty odd, I also have en-gb and it works for me (takes `en`), but the i18n config should say to keep only  the base language

https://github.com/Haroenv/read-one-article/blob/dc6703438a8d13b0f97ac52df700975db5cb711c/src/i18n.js#L15

Do you see any documentation in i18n-next to show what I would have done wrong?

**Comment by Haroenv** [comment]
hmm, I can repro on Chrome (but I couldn't earlier. We'll need to manually strip part of the language)
