### ISSUE TITLE
Language <select> unreadable (white on white)

### ISSUE THREAD

**Issue by 0x04** [Haroenv/read-one-article#6]
Latest Chrome and Window 10 with Dark-Mode enabled.

![image](https://user-images.githubusercontent.com/1921383/78240370-355c6c80-74df-11ea-89c0-02df45120c80.png)

**Comment by Haroenv** [comment]
Ah weird that it allows the color to be set, but not the background color. Can you check whether adding an explicit background color is allowed (instead of `inherit` which I think is used here?

**Comment by Haroenv** [comment]
Maybe the color of the `option` needs to be changed? I'm surprised the default browser controls aren't changed in color due to `light dark` in the meta
